services:
  telegram-bot:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Name the container for easier identification
    container_name: captain_bot
    # Automatically read environment variables from a .env file
    env_file:
      - .env
    # Restart policy to ensure the bot stays online
    restart: unless-stopped
    # Logging configuration to prevent disk space issues
    logging:
      driver: "json-file"
      options:
        # Maximum size of a single log file
        max-size: "10m"
        # Number of log files to keep
        max-file: "5"
    # Add custom DNS servers to resolve potential network issues on the host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Mount a data directory as a volume to persist the SQLite database.
    volumes:
      - ./data:/app/data
